# Generated by Django 4.0.5 on 2022-06-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('Car_Plate_number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Car_Model_year', models.CharField(max_length=4)),
                ('Card_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('Card_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Car_Plate_number', models.CharField(max_length=7)),
                ('Barcode_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('Driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Car_Plate_Number', models.CharField(max_length=7)),
                ('Card_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('Guest_id', models.IntegerField()),
                ('Entry_time', models.DateTimeField()),
                ('Exit_time', models.DateTimeField()),
                ('Address', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('CNIC', models.CharField(max_length=15)),
                ('Phone_Number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Residents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resident_id', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
