# Generated by Django 4.0.5 on 2022-06-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='First_name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Car_Model_year',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Last_name',
        ),
    ]
