# Generated by Django 4.0.5 on 2022-06-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0003_delete_person_remove_residents_id_driver_cnic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Card_id',
        ),
        migrations.AddField(
            model_name='admin',
            name='CNIC',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='Phone_Number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='Car_Plate_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.car'),
        ),
    ]
