# Generated by Django 4.0.5 on 2022-06-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0004_remove_car_card_id_admin_cnic_admin_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='CNIC',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='Car_Plate_Number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.car'),
        ),
        migrations.AddField(
            model_name='guests',
            name='Card_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.card'),
        ),
        migrations.AddField(
            model_name='guests',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='Phone_Number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
