# Generated by Django 4.0.5 on 2022-06-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0006_residents_cnic_residents_car_plate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='Card_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.card'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='Entry_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='Exit_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='residents',
            name='Card_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.card'),
        ),
    ]
