# Generated by Django 4.0.5 on 2022-06-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0008_alter_guests_card_id_alter_residents_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='Car_Plate_Number',
        ),
        migrations.RemoveField(
            model_name='residents',
            name='Car_Plate_Number',
        ),
        migrations.AlterField(
            model_name='guests',
            name='Entry_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='Exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
