# Generated by Django 4.0.5 on 2022-06-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0009_remove_guests_car_plate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='Entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
