# Generated by Django 4.0.5 on 2022-06-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0010_alter_guests_entry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='Car_Plate_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.car'),
        ),
        migrations.AddField(
            model_name='residents',
            name='Car_Plate_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.car'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='Card_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.card'),
        ),
        migrations.AlterField(
            model_name='residents',
            name='Card_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.card'),
        ),
    ]
