# Generated by Django 4.0.5 on 2022-06-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0011_guests_car_plate_number_residents_car_plate_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='Phone_Number',
        ),
    ]
