# Generated by Django 4.0.5 on 2022-06-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0012_remove_guests_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='guests',
            old_name='Name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='residents',
            old_name='Name',
            new_name='First_Name',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='Entry_time',
        ),
        migrations.RemoveField(
            model_name='residents',
            name='Address',
        ),
        migrations.AddField(
            model_name='admin',
            name='Last_Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='House_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='Last_Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='Sector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='Street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='residents',
            name='House_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='residents',
            name='Last_Name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='residents',
            name='Sector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='residents',
            name='Street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
