# Generated by Django 4.0.5 on 2022-06-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0013_rename_name_admin_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
