# Generated by Django 4.0.6 on 2022-07-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0016_temproryresidentdata_delete_temproryresident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temproryresidentdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='temproryresidentdata',
            name='Car_Plate_number',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
