# Generated by Django 4.0.6 on 2022-07-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0018_temproryresident_delete_temproryresidentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='temproryresidentdata',
            fields=[
                ('First_Name', models.CharField(max_length=20, null=True)),
                ('Last_Name', models.CharField(max_length=20, null=True)),
                ('CNIC', models.CharField(max_length=15, null=True)),
                ('Phone_Number', models.BigIntegerField(null=True)),
                ('Car_Name', models.CharField(max_length=30, null=True)),
                ('Car_Plate_number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('House_no', models.CharField(blank=True, max_length=200, null=True)),
                ('Street', models.CharField(blank=True, max_length=200, null=True)),
                ('Sector', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='temproryresident',
        ),
    ]
