# Generated by Django 4.0.6 on 2022-07-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0021_rename_resident_id_temproryresidentdata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temproryresidentdata',
            name='id',
        ),
        migrations.AddField(
            model_name='temproryresidentdata',
            name='R_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
