# Generated by Django 4.0.6 on 2022-07-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0022_remove_temproryresidentdata_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temproryresidentdata',
            name='R_id',
        ),
        migrations.AlterField(
            model_name='temproryresidentdata',
            name='Car_Plate_number',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
