# Generated by Django 4.0.6 on 2022-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0024_temproryresidentdata_r_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temproryresidentdata',
            name='Car_Plate_number',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
