# Generated by Django 4.0.6 on 2022-07-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0026_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='Exit_time',
        ),
    ]
