# Generated by Django 4.0.6 on 2022-07-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0027_remove_guests_exit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='residents',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
