# Generated by Django 4.0.6 on 2022-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0028_guests_type_residents_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='type',
            field=models.CharField(default='resident', max_length=20),
        ),
        migrations.AlterField(
            model_name='residents',
            name='type',
            field=models.CharField(default='resident', max_length=20),
        ),
    ]
