# Generated by Django 4.0.6 on 2022-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0029_alter_guests_type_alter_residents_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Card_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
