# Generated by Django 4.0.6 on 2022-07-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0030_alter_card_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='type',
        ),
        migrations.RemoveField(
            model_name='residents',
            name='type',
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(default='resident', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='Card_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
