# Generated by Django 4.0.6 on 2022-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0031_remove_guests_type_remove_residents_type_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
