# Generated by Django 4.0.6 on 2022-07-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0032_history_entry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='isentered',
            field=models.BooleanField(default=False),
        ),
    ]
