# Generated by Django 4.0.6 on 2022-07-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0035_alter_card_barcode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='static/barcodeimages/'),
        ),
    ]
