# Generated by Django 4.0.6 on 2022-07-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0036_card_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
        migrations.AddField(
            model_name='guests',
            name='type',
            field=models.CharField(default='resident', max_length=20),
        ),
        migrations.AddField(
            model_name='residents',
            name='type',
            field=models.CharField(default='resident', max_length=20),
        ),
    ]
