# Generated by Django 4.0.6 on 2022-07-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0039_remove_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(default='resident', max_length=20),
        ),
    ]
