# Generated by Django 4.0.6 on 2022-07-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0040_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Barcode_id',
            field=models.IntegerField(),
        ),
    ]
