# Generated by Django 4.0.6 on 2022-07-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0041_alter_card_barcode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Barcode_id',
            field=models.IntegerField(unique=True),
        ),
    ]
