# Generated by Django 4.0.5 on 2022-12-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0042_alter_card_barcode_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='Card_id',
        ),
        migrations.RemoveField(
            model_name='residents',
            name='Card_id',
        ),
        migrations.AddField(
            model_name='card',
            name='Guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.guests'),
        ),
        migrations.AddField(
            model_name='card',
            name='Resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.residents'),
        ),
    ]
