# Generated by Django 4.0.5 on 2022-12-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0043_remove_guests_card_id_remove_residents_card_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='Email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='residents',
            name='Email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='residents',
            name='isentered',
            field=models.BooleanField(default=False),
        ),
    ]
