# Generated by Django 4.0.5 on 2022-12-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0046_remove_card_guest_guests_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temproryresidentdata',
            name='Car_Name',
        ),
        migrations.RemoveField(
            model_name='temproryresidentdata',
            name='Car_Plate_number',
        ),
    ]
