# Generated by Django 4.0.5 on 2022-12-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0048_card_temproryresident'),
    ]

    operations = [
        migrations.AddField(
            model_name='temproryresidentdata',
            name='type',
            field=models.CharField(default='resident', max_length=20),
        ),
    ]
