# Generated by Django 4.0.5 on 2022-12-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0049_temproryresidentdata_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='residents',
            name='IsTemporary',
            field=models.BooleanField(default=False),
        ),
    ]
