# Generated by Django 4.0.5 on 2022-12-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0050_residents_istemporary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Temproryresident',
        ),
        migrations.DeleteModel(
            name='temproryresidentdata',
        ),
    ]
