# Generated by Django 4.0.5 on 2022-12-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0051_remove_card_temproryresident_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='Guest_id',
            new_name='Driver_id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='CNIC',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guests',
            name='CNIC',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='residents',
            name='CNIC',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
