# Generated by Django 4.0.5 on 2022-12-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0052_rename_guest_id_history_driver_id_alter_admin_cnic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Card_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyp.card'),
        ),
    ]
