# Generated by Django 4.0.5 on 2022-12-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0053_history_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='isentered',
            field=models.BooleanField(default=False),
        ),
    ]
