# Generated by Django 4.0.5 on 2022-12-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0054_card_isentered'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='isrejected',
            field=models.BooleanField(default=False),
        ),
    ]
